name: Build (Linux)

on:
  push:
    paths:
      - 'CMakeLists.txt'
      - 'source/*'
      - '.github/workflows/linux.yml'
  workflow_dispatch:
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
      with:
        submodules: true
        fetch-depth: 0

    - name: Set up uv
      uses: astral-sh/setup-uv@v8.1.0

    - name: Set up Ninja
      run: pip install ninja

    - name: Set up HIP (Linux)
      run: |
        sudo mkdir -p /etc/apt/keyrings
        wget https://repo.radeon.com/rocm/rocm.gpg.key -O - | \
          gpg --dearmor | sudo tee /etc/apt/keyrings/rocm.gpg > /dev/null

        sudo tee /etc/apt/sources.list.d/rocm.list << 'EOF'
        deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/7.2.4 noble main
        EOF

        sudo tee /etc/apt/preferences.d/rocm-pin-600 << 'EOF'
        Package: *
        Pin: release o=repo.radeon.com
        Pin-Priority: 600
        EOF

        sudo apt-get update
        sudo apt-get install -y rocm-hip-runtime-dev

        echo "PATH=/opt/rocm/bin${PATH:+:${PATH}}" >> $GITHUB_ENV
        echo "ROCM_PATH=/opt/rocm" >> $GITHUB_ENV
        echo "HIP_PATH=/opt/rocm" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=/opt/rocm/lib:/opt/rocm/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" >> $GITHUB_ENV

    - name: Download VapourSynth headers
      run: |
        wget -q -O vs.zip https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R72.zip
        unzip -q vs.zip
        mv vapoursynth*/ vapoursynth

    - name: Configure
      run: cmake -S . -B build -G Ninja
        -D VS_INCLUDE_DIR="`pwd`/vapoursynth/include"
        -D CMAKE_BUILD_TYPE=Release
        -D CMAKE_CXX_FLAGS="-ffast-math"
        -D CMAKE_HIP_ARCHITECTURES="gfx1010;gfx1011;gfx1012;gfx1030;gfx1031;gfx1032;gfx1033;gfx1034;gfx1035;gfx1036;gfx1100;gfx1101;gfx1102;gfx1103;gfx1200;gfx1201"
        -D GPU_TARGETS="gfx1010;gfx1011;gfx1012;gfx1030;gfx1031;gfx1032;gfx1033;gfx1034;gfx1035;gfx1036;gfx1100;gfx1101;gfx1102;gfx1103;gfx1200;gfx1201"

    - name: Build
      run: cmake --build build --config Release --verbose

    - name: Install
      run: cmake --install build --prefix install

    - name: Build wheel
      run: uv build --wheel

    - name: Repair wheel
      run: |
        uvx --with patchelf auditwheel repair --strip dist/*.whl -w repaired_wheels
        rm dist/*.whl
        mv repaired_wheels/*.whl dist/

    - name: Upload wheel
      uses: actions/upload-artifact@v7
      with:
        name: wheel-linux
        path: dist/*.whl
